version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tracky-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your-refresh-secret-key-change-in-production}
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    networks:
      - tracky-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: tracky-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tracky-network

networks:
  tracky-network:
    driver: bridge

volumes:
  backend-data:
