version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tracky-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    volumes:
      - ./backend/data:/app/data
    networks:
      - tracky-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: tracky-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - tracky-network

  nginx:
    image: nginx:alpine
    container_name: tracky-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - tracky-network

  certbot:
    image: certbot/certbot
    container_name: tracky-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  tracky-network:
    driver: bridge